name: aleatunes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  audioplayers: ^6.0.0
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Black.ttf  
          weight: 900
        - asset: assets/fonts/Kanit-ExtraBold.ttf  
          weight: 800
        - asset: assets/fonts/Kanit-Bold.ttf  
          weight: 700
        - asset: assets/fonts/Kanit-SemiBold.ttf  
          weight: 600
        - asset: assets/fonts/Kanit-Medium.ttf  
          weight: 500
        - asset: assets/fonts/Kanit-Regular.ttf  
          weight: 400
        - asset: assets/fonts/Kanit-Light.ttf  
          weight: 300
        - asset: assets/fonts/Kanit-ExtraLight.ttf  
          weight: 200
        - asset: assets/fonts/Kanit-Thin.ttf  
          weight: 100

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/aleatunes.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/aleatunes.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/aleatunes.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/aleatunes.png"


flutter_native_splash:
  background_image: assets/splash.png
  android: true
  ios: true
  web: false

